const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/Eimages/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.8,
      numReview: 8,
      countInStock: 20,
      description: 'A branded shirt for every occassion',
    },

    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/Eimages/shirt2.jpg',
      price: 80,
      brand: 'Raymonds',
      rating: 5.8,
      numReview: 7,
      countInStock: 40,
      description: 'A branded shirt for every occassion',
    },

    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/Eimages/shirt3.jpg',
      price: 90,
      brand: 'Puma',
      rating: 6.8,
      numReview: 9,
      countInStock: 30,
      description: 'A branded shirt for every occassion',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/Eimages/pants1.jpg',
      price: 70,
      brand: 'Oliver',
      rating: 4.8,
      numReview: 8,
      countInStock: 20,
      description: 'A branded Pant for every occassion',
    },

    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/Eimages/pants2.jpg',
      price: 110,
      brand: 'Zara',
      rating: 4.8,
      numReview: 18,
      countInStock: 24,
      description: 'A branded Pant for every occassion',
    },

    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/Eimages/pants3.jpg',
      price: 95,
      brand: 'Casely',
      rating: 2.8,
      numReview: 5,
      countInStock: 20,
      description: 'A branded Pant for every occassion',
    },
  ],
};

export default data;
